server:
  port: 8699

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    organiztionReportPath: /api/mtx/organizations/report