server:
  port: 8654

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true
  rabbitmq:
    host: 192.168.0.207
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.207:27017}
      database: mtx_invoice

management:
  security:
    enable: false

archisoft:
  constant:
    supportEmail: mtxsupport@archisoftglobal.com
    systemEmail:  mtxsystem@archisoftglobal.com
  rabbitmq:
    queue: document
  configuration:
    trans:
      xsltPrefix: _xml2xml.xsl
      xsltPath: /home/tharanga/mtx/xslts/
      outputPath: /home/tharanga/mtx/output/
      outputFileIdentifier: mtx_