server:
  port: 8605

spring:
  profiles:
    active: ft
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.209:27017}
      database: agc_cdm
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

service:
  activityService:
    serviceId:  userActivityService
    addUserActivityPath:  /api/mtx/useractivities

management:
  security:
    enable: false