server:
  port: 8688

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

archisoft:
  organization:
    beforeApproveRejectStatus: WA
  email:
    subject:
      rejectCompany: Company registration fail


