server:
  port: 8602

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.209:27017}
      database: agc_uaa
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

logging:
  file: archisoft-common-userManagement.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d {yyyy-MM-dd HH:mm:ss} - %msg%n"

service:
  emailservice:
    serviceId:  emailService
    gmailApiPath: api/gmail
  userService:
    serviceId:  userservice
    getUsersPath: /api/users/
    getCompanyByUserIdAndCompanyIdAndType:  /api/company/{companyId}/users/{userId}?companyType={companyType}
    getUserGroupById:  /api/usergroups/
    getForgotPasswordActivationPath:  /user/password?email={emailAddress}
    getUsersByEmailPath: /api/users?email=
  activationkey:
    validInSecond: 300

archisoft:
  constant:
    forgotPasswordActivationLink: http://localhost:8080/#/change-password?key=