server:
  port: 8688

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${DB_URL:mongodb://app_user:xpp_user@192.168.0.211:27017}
      database: xfc_lead
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false
