server:
  port: 8685

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${DB_URL:mongodb://app_user:xpp_user@192.168.0.211:27017}
      database: agc_org
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

archisoft:
  organization:
    departmentcode: 9000

  username:
    policy:
      minLength: 8
      maxLength: 30
      regex: ^[a-zA-Z0-9,.@ ]*$



