server:
  port: 8676

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.171:27017}
      database: mtx_credit
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

archisoft:
  rabbitmq:
    notificationExchange: archi.notification
    notificationKey: archi.notificationKey