server:
  port: 8700

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

archisoft:
  configuration:
    ftpHost:  192.168.0.64
    ftpPort:  21
    ftpUser:  ftpuser
    ftpPassword:  ftpuser