spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
    addOrganizationAPIPath: /api/mtx/network
  organizationService:
    serviceId: organizationService
    organizationPath: /api/mtx/organizations/{orgId}
    addOrganizationDetailsPath: /api/mtx/organizations/invite
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/useractivities
  emailservice:
    serviceId: emailService
    emailApiPath: /api/email
    emailNotificationPath: /api/emails
  notificationservice:
    serviceId: notificationservice
    notificationApiPath: /api/ntf/users?orgId={orgId}&event={event}&eventName={eventName}
    addNotificationPath: /api/ntf

archisoft:
  network:
    maxInvitationPerRequest: 10
  organization:
    registrationPath: http://192.168.0.209:3000/#/suppliers/registration
  email:
    requestSupplierSubject: Invitaion for MTx by
    inviteRegisterdSupplierSubject: Invitation to join [BC] Network
    inviteBuyerSubject: Request to join [BC] Network
  dashboard:
    inviteBody: Buyer [BC] has sent an invitation to your company [SC] to join their network.
    inviteBuyerBody: Supplier [SC] has sent a request to be part of your company [BC]’s network.