spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
  organizationServie:
    serviceId: organizationService
    addOrganizationDetailsPath: /api/mtx/organizations/mtx
    organizationPath: /api/mtx/organizations/{orgId}

archisoft:
  network:
    maxInvitationPerRequest: 10