spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
    addOrganizationAPIPath: /api/mtx/network
  organizationService:
    serviceId: organizationService
    organizationPath: /api/mtx/organizations/{orgId}
    addOrganizationDetailsPath: /api/mtx/organizations/invite
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/activities
  emailservice:
    serviceId:  emailService
    emailApiPath: /api/email

archisoft:
  network:
    maxInvitationPerRequest: 10
  organization:
    registrationPath: http://192.168.0.207:3000/#/suppliers/registration
  email:
    requestSupplierSubject: Invitaion for MTx by