#server:
#  port: 0

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
    getSuppliersAdvanceSearchPath: /api/mtx/network/buyer/{buyerId}/advance?
    updateSupplierStatusPath: /api/mtx/network/buyer/{buyerId}/suppliers/{supplierId}/status
    supplierListToBuyerNetwork: /api/mtx/network/buyer/{buyerId}/suppliers
    getBuyerListPath: /api/mtx/network/supplier/{supplierId}/buyers
    getBuyersAdvanceSearchPath: /api/mtx/network/supplier/{supplierId}/advance?
    getsupplierListPath: /api/mtx/network/buyer/
