server:
  port: 8621

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
    addOrganizationAPIPath: /api/mtx/network
  organizationServie:
    serviceId: organizationService
    addOrganizationDetailsPath: /api/mtx/organizations/mtx
    organizationPath: /api/mtx/organizations/{orgId}
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/activities

archisoft:
  network:
    maxInvitationPerRequest: 10





