spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService
  organizationServie:
    serviceId: organizationService
    getByBusinessRegistraitonNumber: /api/mtx/organizations?buzReg={buzReg}

archisoft:
  network:
    maxInvitationPerRequest: 10





