server:
  port: 8635

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  networkService:
    serviceId:  networkService

    getSupplierListPath: /api/mtx/network/buyer/
    getSuppliersAdvanceSearchPath: /api/mtx/network/buyer/advance
    updateSupplierStatusPath: /api/mtx/network/buyer/{buyerId}/suppliers/{supplierId}
    addSuppliersToBuyerNetwork: /api/mtx/network/buyer/{buyerId}/suppliers

    getBuyerListPath: /api/mtx/network/supplier/
    getBuyersAdvanceSearchPath: /api/mtx/network/supplier/advance

#    createbuyerPath: api/mtx/buyers
#    deletebuyerPath: api/mtx/buyers/
#    getbuyerPath: api/mtx/buyers/

