server:
  port: 8691

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    organizationByIDPath: /api/mtx/organizations/{orgId}
  invoiceService:
    serviceId: invoiceService
    invoiceBasePath: /api/mtx/invoices
    invoiceByIdPath: /api/mtx/invoices/{invoiceId}
    invoiceItemsPath: /api/mtx/invoices/{invoiceId}/items
    invoiceBankPath: /api/mtx/invoices/{invoiceId}/banks
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/useractivities