server:
  port: 8691

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    organizationByIDPath: /api/mtx/organizations/{orgId}
  invoiceService:
    serviceId: invoiceService
    invoiceBasePath: /api/mtx/invoices
    invoiceByIdPath: /api/mtx/invoices/{invoiceId}
    invoiceItemsPath: /api/mtx/invoices/{invoiceId}/items
    invoiceRemittancePath: /api/mtx/invoices/{invoiceId}/remittance
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/useractivities
  notificationservice:
    serviceId: notificationservice
    notificationApiPath: /api/ntf/users?orgId={orgId}&event={event}
    addNotificationPath: /api/ntf