spring:
  profiles:
    active: dev
  zipkin:
    sender:
      type: web
    baseUrl:  http://192.168.0.207:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://192.168.0.207:8760/eureka/}

archisoft:
  configuration:
    ftpHost:  192.168.0.207
    ftpPort:  22
    ftpUser:  ftpuser
    ftpPassword:  ftpuser
  constant:
    passwordActivationLink: http://localhost:8080/activate/buyer?key=