spring:
  profiles:
    active: ft
  zipkin:
    sender:
      type: web
    baseUrl:  http://192.168.0.207:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://admin:admin@192.168.0.209:8761/eureka/}

archisoft:
  configuration:
    ftpHost:  192.168.0.207
    ftpPort:  22
    ftpUser:  ftpuser
    ftpPassword:  ftpuser
  constant:
    passwordActivationLink: http://192.168.0.209:3000/activate/buyer?key=
    userActivationLink: http://192.168.0.209:3000/#/user-activation?key=
    adminActivationLink: http://192.168.0.209:4000/#/user-activation?key=
  user:
    adminCompanyId: MY00000A

service:
  commonService:
    serviceId: supportservice
    getCommonCompanyModules: /api/modules?group={group}