server:
  port: 8658

spring:
  profiles:
    active: ft
  zipkin:
    sender:
      type: web
    baseUrl:  http://192.168.0.209:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://192.168.0.55:8760/eureka/}