spring:
  profiles:
    active: ft
  zipkin:
    sender:
      type: web
    baseUrl:  http://192.168.0.212:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.0.212
    port: 5672
    username: app_mq
    password: xpp_mq
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://admin:admin@192.168.0.212:8761/eureka/}

archisoft:
  configuration:
    ftpHost:  192.168.0.212
    ftpPort:  22
    ftpUser:  ftpuser
    ftpPassword:  ftpuser
  constant:
#    passwordActivationLink: http://192.168.0.212:3000/activate/buyer?key=
#    userActivationLink: http://192.168.0.212:3000/user-activation?key=
#    adminActivationLink: http://192.168.0.212:4000/user-activation?key=
    passwordActivationLink: http://202.168.72.43:3000/activate/buyer?key=
    userActivationLink: http://202.168.72.43:3000/user-activation?key=
    adminActivationLink: http://202.168.72.43:4000/user-activation?key=
  user:
    adminCompanyId: MY00000A
  email:
    emailTopic: email-topic
  kafka:
    server: 192.168.0.212:9092
  rabbitmq:
    exchange: archi.direct
    routingkey: archi.routingkey
    failexchange: archi.fail
    failroutingkey: archi.failroutingkey
    queue: archisoft-email
    activityExchange: archi.activity
    activityRoutingKey: archi.activityKey
    activityQueue: archi-activity

service:
  commonService:
    serviceId: supportservice
    getCommonCompanyModules: /api/modules?group={group}