spring:
  profiles:
    active: dev
  zipkin:
    sender:
      type: web
    baseUrl:  http://192.168.0.207:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.0.171
    port: 5672
    username: admin
    password: password
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://admin:admin@192.168.0.171:8761/eureka/}

archisoft:
  configuration:
    ftpHost:  192.168.0.207
    ftpPort:  22
    ftpUser:  ftpuser
    ftpPassword:  ftpuser
  constant:
    passwordActivationLink: http://192.168.0.207:3000/activate/buyer?key=
    userActivationLink: http://192.168.0.207:3000/#/user-activation?key=
    adminActivationLink: http://192.168.0.207:4000/#/user-activation?key=
  user:
    adminCompanyId: MY00000A
  email:
    emailTopic: email-topic
  kafka:
    server: 192.168.0.207:9092
  rabbitmq:
    exchange: archi.direct
    routingkey: archi.routingkey
    failexchange: archi.fail
    failroutingkey: archi.failroutingkey
    queue: archisoft-email

service:
  commonService:
    serviceId: supportservice
    getCommonCompanyModules: /api/modules?group={group}
