server:
  port: 8640

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

logging:
  file: archisoft-mtx-supplierManagement.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d {yyyy-MM-dd HH:mm:ss} - %msg%n"

service:
  emailService:
    serviceId:  emailservice
    gmailApiPath: api/gmail
  userService:
    serviceId:  userservice
    createUserPath: api/users
    createUserGroupPath: api/usergroups
  supplierService:
    serviceId:  supplierservice
    createSupplierPath: api/supplier

archisoft:
  constant:
    passwordActivationLink: http://localhost:8080/activate/supplier?key=