server:
  port: 8640

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  emailService:
    serviceId:  emailservice
    gmailApiPath: api/gmail
  userService:
    serviceId:  userservice
    createUserPath: api/users
    deleteUserPath: api/users/
    createUserGroupPath: /api/usergroups
    deleteUserGroupPath: api/usergroups/
  supplierService:
    serviceId:  supplierservice
    createSupplierPath: /api/mtx/suppliers
    deleteSupplierPath: api/mtx/suppliers/
    getSupplierPath: /api/mtx/suppliers/{supplierId}
    updateSupplierStep2Path: /api/mtx/suppliers/{id}/step2
    updateSupplierContactPath: /api/mtx/suppliers/{id}/contacts
    editSupplierContactPath: /api/mtx/suppliers/{id}/contacts/{contactId}
    supplierRemittancePath: /api/mtx/suppliers/{id}/remittance
    supplierBankPath: /api/mtx/suppliers/{id}/banks
    supplierShipInfoPath: /api/mtx/suppliers/{id}/shipfrom
    editSupplierShipInfoPath: /api/mtx/suppliers/{id}/shipfrom/{shipId}
    supplierTaxInfoPath: /api/mtx/suppliers/{id}/tax
    editSupplierTaxInfoPath: /api/mtx/suppliers/{id}/tax/{taxId}
    supplierUmoInfoPath: /api/mtx/suppliers/{id}/uoms
    supplierCurrencyPath: /api/mtx/suppliers/{id}/currencies
    supplierPreferencePath: /api/mtx/suppliers/{id}/preference
    updateSupplierDocumentPath: /api/mtx/suppliers/{supplierId}/documents
    getSupplierDocumentPath: /api/mtx/suppliers/{supplierId}/documents?type={type}
    deleteSupplierDocumentPath: /api/mtx/suppliers/{supplierId}/documents?docName={docName}
    editSupplierStatus: /api/mtx/suppliers/{supplierId}/status

archisoft:
  constant:
    passwordActivationLink: http://localhost:8080/activate/supplier?key=