server:
  port: 8601

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.209:27017}
      database: agc_uaa
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

logging:
  file: archisoft-common-user.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d {yyyy-MM-dd HH:mm:ss} - %msg%n"

service:
  emailservice:
    serviceId:  emailService
    gmailApiPath: api/gmail
  activationkey:
    validInSecond: 300