eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.207:8762/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.207:27017
      database: agc_cdm
  profiles:
    active: dev