server:
  port: 8601

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://app_user:xpp_user@192.168.0.212:27017}
      database: agc_uaa
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

service:
  emailservice:
    serviceId:  emailService
    gmailApiPath: api/gmail
  activationkey:
    validInSecond: 300

archisoft:
  constant:
    forgotPasswordActivationLink: http://localhost:8080/#/change-password?key=