server:
  port: 8680

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    selfRegistrationPath: /api/mtx/organizations/self
    deleteOrganizationPath: /api/mtx/organizations/{orgId}
    updateOrganizationDocumentPath: /api/mtx/organizations/{orgId}/documents
    organizationPath: /api/mtx/organizations/{orgId}
    changeOrganizationStatusPath: /api/mtx/organizations/{orgId}/status
    updateOrganizationImage: /api/mtx/organizations/{orgId}/image
   activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/activities
  userService:
    serviceId:  userservice
    createUserGroupPath:  /api/usergroups
    userGroupPath:  /api/usergroups/{groupId}
    deleteUserCompany:  /api/users/{userId}?companyId={companyId}
  userMgtService:
    serviceId:  usermgtservice
    createUserPath:  /api/users
  emailservice:
    serviceId:  emailService
    emailApiPath: /api/email
  commonService:
    serviceId: supportservice
    menuByType : /api/menu/{id}?type={type}

archisoft:
  organization:
    beforeApproveRejectStatus: WA
  email:
    subject:
      rejectCompany: Company registration fail