server:
  port: 8680

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    selfRegistrationPath: /api/mtx/organizations/self
    deleteOrganizationPath: /api/mtx/organization/{orgId}
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/activities
  oraganizationService:
    updateOrgStep2Path: /api/mtx/buyers/{id}/step2
