server:
  port: 8680

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    selfRegistrationPath: /api/mtx/organizations/self
    organizationPath: /api/mtx/organization/{orgId}
    updateOrganizationDocumentPath: /api/mtx/organization/{orgId}/documents
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/activities
  userService:
    serviceId:  userservice
    createUserGroupPath:  /api/usergroups
    userGroupPath:  /api/usergroups/{groupId}
    deleteUserCompany:  /api/users/{userId}?companyId={companyId}
  userMgtService:
    serviceId:  usermgtservice
    createUserPath:  /api/users

archisoft:
  organization:
    beforeApproveRejectStatus: WA