server:
  port: 8620

spring:
  profiles:
    active: ft
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.207:27017}
      database: mtx_supplier
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  emailService:
    serviceId:  emailservice
    gmailApiPath: api/gmail
  userService:
    serviceId: userservice



