server:
  port: 8671

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

service:
  notificationservice:
    serviceId: notificationservice
    addNotificationPath: /api/ntf
    notificationApiPath: /api/ntf/users?orgId={orgId}&event={event}
  emailservice:
    serviceId: emailservice
    emailsApiPath: /api/emails

security:
  ignored=/**

management:
  security:
    enable: false