server:
  port: 8662

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://app_user:xpp_user@192.168.0.212:27017}
      database: agc_log
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**


management:
  security:
    enable: false
