server:
  port: 8696

spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    organizationByIDPath: /api/mtx/organizations/{orgId}
  purchaseOrderService:
    serviceId: purchaseOrderService
    purchaseOrderBasePath: /api/mtx/po
    purchaseOrderByIdPath: /api/mtx/po/{poId}
    purchaseOrderItemsPath: /api/mtx/po/{poId}/items
    purchaseOrderStatusPath: /api/mtx/po/{poId}/status
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/useractivities
  notificationservice:
    serviceId: notificationservice
    notificationApiPath: /api/ntf/users?orgId={orgId}&event={event}
    addNotificationPath: /api/ntf