server:
  port: 8696

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

service:
  organizationService:
    serviceId:  organizationService
    organizationByIDPath: /api/mtx/organizations/{orgId}
  purchaseOrderService:
    serviceId: purchaseOrderService
    purchaseOrderBasePath: /api/mtx/po
    purchaseOrderByIdPath: /api/mtx/po/{poId}
    purchaseOrderItemsPath: /api/mtx/po/{poId}/items
  activityService:
    serviceId:  userActivityService
    addActivityPath:  /api/mtx/useractivities