server:
  port: 8650

spring:
  profiles:
    active: ft
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

management:
  security:
    enable: false

logging:
  file: archisoft-mtx-buyerManagement.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d {yyyy-MM-dd HH:mm:ss} - %msg%n"

service:
  emailService:
    serviceId:  emailservice
    gmailApiPath: api/gmail
  userService:
    serviceId:  userservice
    createUserPath: api/users
    deleteUserPath: api/users/
    createUserGroupPath: api/usergroups
    deleteUserGroupPath: api/usergroups/
  buyerService:
    serviceId:  buyerservice
    createbuyerPath: api/mtx/buyers
    deletebuyerPath: api/mtx/buyers/
    getbuyerPath: api/mtx/buyers/
    updateBuyerStep2Path: /api/mtx/buyers/{id}/step2
    updateBuyerInvoiceRulePath: /api/mtx/buyers/{id}/ir
    updateBuyerRelationshipConfigPath: /api/mtx/buyers/{id}/sr
    updateBuyerShippingInfoPath: /api/mtx/buyers/{id}/sp
    updateBuyerTaxInfoPath: /api/mtx/buyers/{id}/tx
    updateBuyerUomInfoPath: /api/mtx/buyers/{id}/uom
    updateBuyerPreferenceInfoPath: /api/mtx/buyers/{id}/pf
    updateBuyerCurrencyInfoPath: /api/mtx/buyers/{id}/cur

archisoft:
  constant:
    passwordActivationLink: http://localhost:8080/activate/buyer?key=