spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.207:27017}
      database: agc_audit
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false

logging:
  file: archisoft-common-audit.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d {yyyy-MM-dd HH:mm:ss} - %msg%n"