server:
  port: 9090

spring:
  profiles:
    active: dev

management:
  security:
    enable: false

ribbon:
  eureka:
    enabled:  true
  host:
    connectTimeoutMillis: 600000
    socketTimeoutMillis:  600000
  ReadTimeout:  30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  120000
zuul:
  sensitive-headers: Cookie,Set-Cookie

archisoft:
  jwtToken:
    secretKey:  my-secret-token-to-change-in-production

mtx:
  services:
    nonsecure:
      (/userservice/api/user/linkvalidity)|(/usermgtservice/user/+(authenticate|password|resetpwd|activate|logout))|(/supportservice/api/+(countries|biznature|uoms))|(/organizationmgtservice/api/organizations/self)|(/supportservice/api/countries/+[A-Z]{2,3}+/states)