server:
  port: 8670

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://192.168.0.207:27017}
      database: agc_ntf
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

service:
  notificationservice:
    serviceId: notificationservice
  emailservice:
    serviceId: emailService
    emailsApiPath: /api/emails

security:
  ignored=/**

management:
  security:
    enable: false