server:
  port: 8670

spring:
  data:
    mongodb:
      uri: ${DB_URL:mongodb://app_user:xpp_user@192.168.0.211:27017}
      database: agc_ntf
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: true

security:
  ignored=/**

management:
  security:
    enable: false